package.json, yarn.lock
https://github.com/coderplex/coderplex/issues/13
https://coderplex-pr-14.now.sh/
=> upgraded react and next

components/row-events.js
Resolves: #16 
Can you check my PR? please :pray:
=> Fix typo on attribute target

CONTRIBUTING.md
PR for the issue #21 
@M-ZubairAhmed Please review. Thanks.
=> Test deploy guidelines

components/header.js
Reverts coderplex/coderplex#33
The auto deploy from #31 (https://coderplex-app-zhjtaipwuc.now.sh/) does not have this problem so reverting this.
=> Revert "Z-index glitch"

components/header.js
This reverts commit 972f6ca2bc7e8a398cad1f7014251c43b6a8447d.
=> Revert "Revert "Z-index glitch" (#35)"

components/global-styles.js, pages/events.js, pages/index.js, utils/urls.js
- links to learn repo syllabus added except for laravel 
- subscribe button added (Without Func)
- fixed bug- center prop on card in index.js
- name of events url changed
=> Some editing to index page

components/header.js, components/row-events.js, components/top-banner.js, package.json, pages/events.js, pages/space.js, yarn.lock
1. top-banner component separated out
2. top-banner included in events and space page
=> space page initial construct 

components/subscribe.js, pages/index.js
Hi,
happy hacktoberfest, this is my take on issue #40. I moved the Subscribe Section to  a seperate component. Since it uses in-component-styles may some css classes are doubled, so another issue can be to solve this. I have not much experience with in-component-styles because most projects I still stick to the "old" way with seperate files (and because the use of sass/less).
I also fixed the error property on the semantic ui form. It takes a bool to show the error Message.
let me know if something is missing or should be corrected, I'll happy to do that.
I hat looked into the issues linked in #40, but one is already closed and the other for styling suggestions, well I quite like like it looks now and I'm sadly not a design geek and have no better idea of styling. May the footer …
=> Move Subscribe to extern component

pages/index.js, pages/space.js
Hacktoberfest contribution, hope it helps!
=> Correcting some spelling mistakes and typos

components/row-events.js, pages/index.js, pages/learn.js
=> learn page initial contruction

pages/index.js, pages/learn.js
Fix issue https://github.com/coderplex/coderplex/issues/54
=> Change headline in /learn

.github/config.yml
Ref: https://github.com/behaviorbot/request-info?installation_id=65121#usage
Installed app: https://github.com/organizations/coderplex/settings/installations/65121
=> configure request-info-bot

README.md
Added License badge
and created a PR
=> Add License badge

components/footer.js
Removed meetup link from the footer of the app. And replaced it with Twitter
=> Fixes #96 and #94

CONTRIBUTING.md
* little bit on nvm
* added nvm instructions, new issues docs
* completed contributing
* error added and indent spaces
* index fix
* branching system added
* sectios rearranged
* start removed
* removed extra section of branching model
* fix of https://github.com/coderplex/coderplex/pull/105#pullrequestreview-77076077
=> Merge master to develop

.github/CONTRIBUTING.md
Fixes #110
Added an Index for Contributing.md
=> add index to contributing.md

components/events/event-card.js, yarn.lock
Fix the icons in event cards.
The icons are misaligned to the text.
The icons are aligned to the text.
=> Added margin-bottom to icons in event-cards

pages/events.js
=> Fixes #119

pages/events.js
=> Fix `Load More` button in `Upcoming Meetups` section

components/events/event-card.js, pages/events.js, pages/index.js
=> show upcoming event on landing page

pages/learn/subject.js, utils/mock-data.js
fixes https://github.com/coderplex/coderplex/issues/131
=> react added

components/common/header/index.js, components/learn/subject-card.js, components/learn/subject-marked.js, components/learn/syllabus-tree/syllabus-tree-container.js, next.config.js, pages/index.js, pages/learn/subject.js, pages/login.js, server.js, utils/mock-data.js
- fixes #136
- fixes #139
- closes #125
=> Chapter pages and few small changes

components/learn/subject-banner.js, package.json, yarn.lock
fixes https://github.com/coderplex/coderplex/issues/117
=> Align title and subtitle for subject page to left for the Responsive case of Tablets

.travis.yml, package.json, renovate.json, yarn.lock
=> Update Deps, remove greenkeeperbot and add renovate bot

components/common/header/index.js
=> update nav link text

.babelrc, components/common/header/index.js, config/meta-info.json, next.config.js, pages/join.js
=> Embed airtable join form

pages/join.js
=> add loader in join page

components/common/header/index.js, config/meta-info.json, next.config.js, pages/members.js
=> Add jobs link to header

pages/events.js
=> Separate tabs for upcoming and recent events

README.md
Changes the README title to "Coderplex Org Website"
Currently just says "Coderplex Website"
=> Add 'org' to README title
